version: '3.7'

services:

    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./frontend:/usr/share/nginx/html

    api:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --reload --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
            - appdata:/var/www/
volumes:
    appdata:
        driver: local